# =============================================================================
# update-media.ps1 - scans projects/*/ and generates js/media-manifest.js
# Run this (or double-click update-media.bat) after adding/removing any media.
# The site then shows whatever files exist - no need to list filenames anywhere.
# =============================================================================

$root = $PSScriptRoot
$projectsDir = Join-Path $root "projects"
$outFile = Join-Path $root "js\media-manifest.js"

$imgExt = @(".jpg", ".jpeg", ".png", ".webp", ".gif")
$vidExt = @(".mp4", ".webm", ".mov")

$manifest = [ordered]@{}

Get-ChildItem $projectsDir -Directory | Sort-Object Name | ForEach-Object {
    $slug = $_.Name
    $p = $_.FullName

    $entry = [ordered]@{ cover = $null; photos = @(); videos = @(); shorts = @() }

    # cover.* in the project root (any image extension)
    $cover = Get-ChildItem $p -File | Where-Object { $_.BaseName -ieq "cover" -and $imgExt -contains $_.Extension.ToLower() } | Select-Object -First 1
    if ($cover) { $entry.cover = $cover.Name }

    foreach ($sub in @("photos", "videos", "shorts")) {
        $dir = Join-Path $p $sub
        if (Test-Path $dir) {
            $ext = if ($sub -eq "photos") { $imgExt } else { $vidExt }
            $files = Get-ChildItem $dir -File | Where-Object { $ext -contains $_.Extension.ToLower() } | Sort-Object Name
            $entry[$sub] = @($files | ForEach-Object { "$sub/$($_.Name)" })
        }
    }

    # no explicit cover -> first photo becomes the card thumbnail
    if (-not $entry.cover -and $entry.photos.Count -gt 0) { $entry.cover = $entry.photos[0] }

    $manifest[$slug] = $entry
}

# Write as a JS file the site loads before app.js
$json = $manifest | ConvertTo-Json -Depth 5
if ($manifest.Count -eq 0) { $json = "{}" }
$js = "// AUTO-GENERATED by update-media.ps1 - do not edit by hand. Re-run the script after adding media.`nwindow.MEDIA_MANIFEST = $json;`n"
Set-Content -Path $outFile -Value $js -Encoding utf8

Write-Host "media-manifest.js updated:"
foreach ($k in $manifest.Keys) {
    $e = $manifest[$k]
    $n = $e.photos.Count + $e.videos.Count + $e.shorts.Count
    if ($n -gt 0 -or $e.cover) { Write-Host ("  {0}: {1} photos, {2} videos, {3} shorts, cover={4}" -f $k, $e.photos.Count, $e.videos.Count, $e.shorts.Count, $e.cover) }
}
